# Generated by Django 5.0.6 on 2024-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visaul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=10)),
                ('intensity', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.CharField(max_length=100)),
                ('added', models.DateTimeField()),
                ('published', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('relevance', models.CharField(max_length=10)),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('likelihood', models.CharField(max_length=100)),
            ],
        ),
    ]
